import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id 'com.android.application'
    id "androidx.navigation.safeargs"
    id 'kotlin-android'
    id 'com.google.devtools.ksp'
    id 'dagger.hilt.android.plugin'
    id 'com.google.firebase.crashlytics'
    id 'org.jetbrains.kotlin.plugin.compose'
    id 'com.google.gms.google-services'  // Google Services plugin
}

apply from: "${rootDir}/ScatterRoutingService/scatterbrainSDK/scripts/version.gradle"

android {

    defaultConfig {
        applicationId "net.ballmerlabs.scatterroutingservice"
        minSdkVersion 26
        targetSdkVersion 36
        versionCode 88
        compileSdk 36

        javaCompileOptions {
            annotationProcessorOptions {
                arguments += [
                        "room.incremental": "true",
                        "room.schemaLocation": "$projectDir/schemas".toString()
                ]
            }
        }
        ksp {
            arg("room.incremental", "true")
            arg("room.schemaLocation", "$projectDir/schemas")
        }

        versionName projectVersionName

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    packagingOptions {
        resources {
            pickFirsts += ['META-INF/com.google.dagger_dagger.version']
        }
        jniLibs {
            useLegacyPackaging true
        }
    }


    buildTypes {
        release {
            minifyEnabled false
            //proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }
        debug {
            minifyEnabled false
            enableUnitTestCoverage true
            enableAndroidTestCoverage true
        }
    }

    apply from: "../ScatterRoutingService/scatterbrainSDK/gradle/jacoco.gradle"


    namespace 'net.ballmerlabs.scatterroutingservice'


    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }

    buildFeatures {
        compose = true
    }

    composeOptions {
        kotlinCompilerExtensionVersion = "1.5.15"
    }

    java {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_21
        freeCompilerArgs = [
                "-Xstring-concat=inline"
        ]
    }
    lint {
        abortOnError false
        checkReleaseBuilds false
        disable 'JvmStaticProvidesInObjectDetector', 'FieldSiteTargetOnQualifierAnnotation', 'ModuleCompanionObjects', 'ModuleCompanionObjectsNotInModuleParent'
    }
}

/*
tasks.withType(KotlinCompile).configureEach {
    compilerOptions.freeCompilerArgs.addAll(
            "-P",
            "plugin:androidx.compose.compiler.plugins.kotlin:reportsDestination=/Users/khanson/Documents/repos/scatter/",
    )
}
 */

dependencies {
    implementation libs.hilt.navigation.compose
    implementation libs.androidx.material3
    implementation "androidx.compose.foundation:foundation:$compose_version"
    implementation "androidx.compose.ui:ui-tooling-preview:$compose_version"
    implementation "androidx.compose.ui:ui:$compose_version"
    implementation libs.navigation.compose
    implementation libs.androidx.paging.compose
    implementation libs.androidx.activity.compose
    implementation libs.appcompat
    implementation libs.androidx.runtime.livedata
    implementation libs.kotlinx.collections.immutable
    implementation libs.material
    implementation libs.constraintlayout
    implementation libs.androidx.navigation.fragment.ktx
    implementation libs.androidx.navigation.ui.ktx
    implementation libs.lifecycle.livedata.ktx
    implementation libs.lifecycle.viewmodel.ktx
    implementation project(':ScatterRoutingService:app')
    implementation project(':scatterbrainSDK')
    implementation libs.androidx.preference.ktx
    implementation libs.androidx.legacy.support.v4
    implementation libs.androidx.recyclerview
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
    implementation libs.material
    implementation libs.androidx.activity.ktx
    implementation libs.fragment.ktx
    implementation libs.kotlin.bip39
    implementation libs.core.ktx
    implementation libs.kotlin.stdlib
    implementation libs.hilt.android
    ksp "com.google.dagger:hilt-compiler:$hilt_version"
    implementation libs.android.identicons
    implementation libs.google.firebase.crashlytics
    implementation libs.androidx.startup.runtime
    implementation libs.androidx.preference.ktx
    implementation libs.accompanist.permissions
    implementation libs.androidx.datastore.preferences
   //implementation "androidx.graphics:graphics-shapes:1.0.0-beta01"

    // Room
    implementation libs.room.runtime
    ksp libs.room.compiler
    implementation libs.room.ktx

}
repositories {
    mavenCentral()
    google()
    maven { url "https://jitpack.io" }
    gradlePluginPortal()
}